apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kafka-broker-display
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "5"
    spec:
      containers:
        - image: quay.io/matzew/event-display
