apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: testevents-trigger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.kafka.event
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kafka-broker-display
