apiVersion: sources.knative.dev/v1alpha1
kind: PingSource
metadata:
  name: test-ping-source
spec:
  schedule: "*/1 * * * *"
  data: '{"message": "Hello, Red Hat Developer!"}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: ping-display
